### ISSUE TITLE
??PARSE ERROR ON LINE 120

### ISSUE THREAD

**Issue by 8bitchipbits** [JoystickAndCursorKeys/basic64-js#118]
Trying samples from https://retrogamestart.com/answers/learn-commodore-64-basic-programming-type-text-based-games
This one errors at line 120

10 REM - THIS NUMBER GUESSING GAME IS BASED ON GUESS AND HI-LO
20 REM - FROM DAVID H. AHL'S BOOK BASIC COMPUTER GAMES.
30 PRINT "======="
40 PRINT " ZERO!"
50 PRINT "=======":PRINT
60 PRINT "I CHOOSE A NUMBER BETWEEN 1 AND 100.":PRINT
70 PRINT "YOU MUST ZERO IN ON IT IN 7 GUESSES.":PRINT
80 PRINT "I TELL YOU TO GUESS HIGHER, OR LOWER.":PRINT
90 INPUT "PRESS ENTER TO START. READY"; START$
100 NUM = INT(100*RND(1))
110 PRINT:PRINT "====================":PRINT
120 PRINT "I HAVE CHOSEN A NUMBER ":PRINT:NUM
130 FOR COUNT = 1 TO 7
140 PRINT "GUESS ";COUNT;
150 INPUT ": "; GUESS$
160 GUESS = VAL(GUESS$)
170 IF GUESS = NUM GOTO 250
180 IF GUESS > NUM THEN PRINT "GUESS LOWER"
190 IF GUESS < NUM THEN PRINT "GUESS HIGHER"
200 PRINT
210 NEXT COUNT
220 PRINT:PRINT "YOU'VE USED ALL OF YOUR GUESSES."
230 PRINT "THE NUMBER WAS";NUM
240 GOTO 270
250 PRINT "YOU GOT IT IN ";COUNT;
260 PRINT " GUESSES."
270 PRINT
280 INPUT "PLAY AGAIN? (Y/N) "; A$
290 IF A$ = "Y" THEN GOTO 100
300 END

**Comment by cursorkeys** [comment]
Hi @8bitchipbits 

Thanks for testing!

I think line 120 is not proper basic.  I had this one tested earlier as well.

120 PRINT "I HAVE CHOSEN A NUMBER ":PRINT:NUM

PRINT:NUM -> results in PRINT and then new command NUM.

I think it's a typo.  
If I change it to 
  PRINT NUM  , the program works.
  
But it also shows the value, which I also think is wrong, since then it's not a guessing game anymore ;)

Check: https://joystickandcursorkeys.github.io/basic64-js/index.html?linkpgm=https%3A%2F%2Fraw.githubusercontent.com%2FJoystickAndCursorKeys%2Fbasic64-js%2Fmain%2Fdoc%2Fguessing.bas

and: 

https://raw.githubusercontent.com/JoystickAndCursorKeys/basic64-js/main/doc/guessing.bas

**Comment by 8bitchipbits** [comment]
Yes! Thanks, just reminding myself not to assume sites with source code are bug free & I should double check first!
